namespace CyberpunkGenerator.Models
{
    public class City
    {
        public string Name { get; set; }
        public List<Neighborhood> Neighborhoods { get; set; }
        public List<Gang> Gangs { get; set; }

        /// <summary>
        /// Total transportation points generated by all pop patronage links
        /// (passenger mobility demand). Populated after ZoningEngine completes.
        /// </summary>
        public float PopTransportationPoints { get; set; }

        /// <summary>
        /// Total transportation points generated by all business-to-business
        /// contracts (freight demand). Populated after ZoningEngine completes.
        /// </summary>
        public float FreightTransportationPoints { get; set; }

        /// <summary>
        /// Combined transportation points across all links.
        /// </summary>
        public float TotalTransportationPoints => PopTransportationPoints + FreightTransportationPoints;

        public City()
        {
            Name = "";
            Neighborhoods = new List<Neighborhood>();
            Gangs = new List<Gang>();
        }
    }
}