using CyberpunkGenerator.Data;

namespace CyberpunkGenerator.Models
{
    /// <summary>
    /// Represents a supply agreement between two businesses.
    /// A Contract is bidirectional: the consumer holds a reference to the
    /// supplier, and the supplier holds a reference back to the consumer.
    /// Quantity represents the units-per-cycle of the good being supplied.
    /// </summary>
    public class Contract
    {
        /// <summary>The business receiving the good.</summary>
        public Business Consumer { get; }

        /// <summary>The business supplying the good.</summary>
        public Business Supplier { get; }

        /// <summary>The specific good being transferred.</summary>
        public MarketGood Good { get; }

        /// <summary>Units per cycle transferred under this contract.</summary>
        public float Quantity { get; }

        /// <summary>
        /// Manhattan distance between supplier and consumer blocks at the time
        /// the contract was formed. Set after both parties are placed.
        /// </summary>
        public int Distance { get; set; }

        /// <summary>
        /// Transportation points generated by this contract.
        /// Quantity * Distance. Calculated once Distance is known.
        /// </summary>
        public float TransportationPoints => Quantity * Distance;

        public Contract(Business consumer, Business supplier, MarketGood good, float quantity)
        {
            Consumer = consumer;
            Supplier = supplier;
            Good = good;
            Quantity = quantity;
        }

        public override string ToString() =>
            $"Contract: {Consumer.BusinessType} ← {Quantity:N0} {Good} ← {Supplier.BusinessType} (dist {Distance}, TP {TransportationPoints:N0})";
    }
}