using CyberpunkGenerator.Data;

namespace CyberpunkGenerator.Models
{
    /// <summary>
    /// Represents a consumer relationship between a Pop and a Business.
    /// A Patronage is bidirectional: the pop holds a reference to the business
    /// it patronizes, and the business holds a reference back to the pop.
    /// Quantity represents the units-per-cycle of the good being consumed.
    /// A single pop may have multiple Patronage links for the same good type
    /// if no single business can fulfill its entire need.
    /// </summary>
    public class Patronage
    {
        /// <summary>The pop consuming the good.</summary>
        public Pop Consumer { get; }

        /// <summary>The business fulfilling the need.</summary>
        public Business Supplier { get; }

        /// <summary>The specific good being consumed.</summary>
        public MarketGood Good { get; }

        /// <summary>Units per cycle consumed under this patronage link.</summary>
        public float Quantity { get; }

        /// <summary>
        /// Manhattan distance between the pop's block and the supplier block
        /// at the time the patronage was formed.
        /// </summary>
        public int Distance { get; set; }

        /// <summary>
        /// Transportation points generated by this patronage link.
        /// Quantity * Distance. Calculated once Distance is known.
        /// </summary>
        public float TransportationPoints => Quantity * Distance;

        public Patronage(Pop consumer, Business supplier, MarketGood good, float quantity)
        {
            Consumer = consumer;
            Supplier = supplier;
            Good = good;
            Quantity = quantity;
        }

        public override string ToString() =>
            $"Patronage: {Consumer} ← {Quantity:N0} {Good} ← {Supplier.BusinessType} (dist {Distance}, TP {TransportationPoints:N0})";
    }
}